modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "hydrogenmod"
version = "R2-1.0.0"
displayName = "HydrogenMod"
authors = "stouma915"
description = "Add hydrogen to Minecraft"

[[dependencies.hydrogenmod]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hydrogenmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
